### ISSUE TITLE
unbound local error

### ISSUE THREAD

**Issue by malleswar22** [higgicd/Accessibility_Toolbox#6]
I got an unbound local error while using the multiprocessing tool. Then I used tool without multi processing. I got the same error. Please help me with how to rectify.

"Start Time: Tuesday, November 30, 2021 11:29:56 AM
There are 16 cpu cores on this machine, using 15
Batching 215 chunks of origins
origins_i is already points...
Calculating origins_i Network Locations...
Finished pre-processing origins_i
destinations_j is already points...
Calculating destinations_j Network Locations...
Finished pre-processing destinations_j
Sending batch to multiprocessing pool...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\malle\Documents\Accessibility_Toolbox-master\Accessibility_Toolbox-master\access_calc_main.py", line 319, in access_multi
    arcpy.management.AddField(od_lines, "Ai_"+f_name, "DOUBLE")
UnboundLocalError: local variable 'od_lines' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 306, in execute
  File "C:\Users\malle\Documents\Accessibility_Toolbox-master\Accessibility_Toolbox-master\access_calc_main.py", line 404, in main
    result = pool.map(access_multi, jobs)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\multiprocessing\pool.py", line 657, in get
    raise self._value
UnboundLocalError: local variable 'od_lines' referenced before assignment
Failed to execute (AccessCalcProMP).
Failed at Tuesday, November 30, 2021 11:39:38 AM (Elapsed Time: 9 minutes 41 seconds)"

**Comment by higgicd** [comment]
the `local variable 'od_lines' referenced before assignment` issue occurs when a particular batch returns no results, for example when no destinations can be found for any origins in the batch. This usually happens when there are network errors and the like. I have updated the tool to ignore null results rather than crash, but this doesn't help address the root issue.
